<<<<<<< HEAD
// ===== WARNING: This file is auto-generated by scripts/generate-entries.js on each build. =====
// It's checked in so your project runs out-of-the-box, but any edits here will be overwritten.
// The generator safely imports every JS module under src/js and calls module.init() if present.

import * as mod_3d_stack from './3d-stack.js';
import * as mod_progress_indicator from './progress-indicator.js';

export function initLib() {
  if (typeof mod_3d_stack.init === 'function') { try { mod_3d_stack.init(); } catch (e) { console.warn('init failed for 3d-stack:', e); } }
  if (typeof mod_progress_indicator.init === 'function') { try { mod_progress_indicator.init(); } catch (e) { console.warn('init failed for progress-indicator:', e); } }
}
=======
// auto-generated, do not edit manually
>>>>>>> 3af09dfe8ad140838f44df1b0766c67f9afd32ee
