name: Build Library

on:
  push:
    branches: [ main ]
    paths:
      - "lib/src/**"
      - "lib/scripts/**"
      - "lib/rollup.config.js"
      - "lib/package.json"
      - "lib/package-lock.json"
      - "lib/.github/workflows/build.yml"

permissions:
  contents: write

concurrency:
  group: build-lib-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lib

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: lib/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Detect dist changes
        id: changes
        shell: bash
        run: |
          if git status --porcelain dist | grep .; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit and push dist
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f dist/lib.min.js dist/lib.min.css
          git commit -m "chore(build): auto-update dist [skip ci]"
          git push origin HEAD:main
