name: Build Library

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install

      - name: Run build script
        run: |
          echo "Building project..."
          npm run build || { echo "❌ Build failed"; exit 1; }

      - name: Verify dist files exist
        run: |
          if [ ! -f dist/lib.min.js ] || [ ! -f dist/lib.min.css ]; then
            echo "❌ Missing built files in dist/"
            exit 1
          fi
          echo "✅ Dist files confirmed"

      - name: Commit and push built dist files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f dist/lib.min.js dist/lib.min.css
          git commit -m "chore(build): auto-update dist [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main || echo "No changes to push"
