name: Build Library

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Debug workspace
        run: |
          echo "========= PROJECT FILES ========="
          ls -R
          echo "================================="

      - name: Run Rollup build
        run: |
          echo "Starting Rollup build..."
          npm run build || { echo "❌ Rollup build failed. Printing files..."; ls -R; exit 1; }

      - name: Verify dist output
        run: |
          if [ -f dist/lib.min.js ] && [ -f dist/lib.min.css ]; then
            echo "✅ Dist files verified."
          else
            echo "❌ dist output missing"
            exit 1
          fi

      - name: Commit and push built dist files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f dist/lib.min.js dist/lib.min.css
          git commit -m "chore(build): auto-update dist [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main || echo "No changes to push"
